---
name: Text-Indent
version: 0.02
author:
  - 'James FitzGibbon, E<lt>jfitz@CPAN.orgE<gt>'
abstract: simple indentation of text shared among modules
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::MethodMaker: 1.12
  Params::Validate: 0.5
provides:
  Text::Indent:
    file: lib/Text/Indent.pm
    version: 0.02
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
